sudo apt-get -y install git cmake
sudo apt-get -y install compton
sudo apt-get -y install openbox
sudo apt-get -y install libfm-dev
sudo apt-get -y install libasound2-dev
sudo apt-get -y install automake
sudo apt-get -y install gtk-doc-tools
sudo apt-get -y install libkf5guiaddons-dev
sudo apt-get -y install libkf5windowsystem-dev
sudo apt-get -y install libconfig-dev
sudo apt-get -y install libdbusmenu-qt5-dev
sudo apt-get -y install libexif-dev
sudo apt-get -y install libkf5solid-dev
sudo apt-get -y install libstatgrab-dev
sudo apt-get -y install libudev-dev
sudo apt-get -y install libsensors4-dev
sudo apt-get -y install openbox-dev
sudo apt-get -y install libpolkit-qt5-1-dev
sudo apt-get -y install libpolkit-agent-1-dev
sudo apt-get -y install libpulse-dev
sudo apt-get -y install valac
sudo apt-get -y install libxcb-damage0-dev
sudo apt-get -y install libxcb-dpms0-dev
sudo apt-get -y install libxcb-screensaver0-dev
sudo apt-get -y install libxcb-util0-dev
sudo apt-get -y install qtbase5-private-dev
sudo apt-get -y install liboobs-1-dev
sudo apt-get -y install libxkbcommon-x11-dev
sudo apt-get -y install libxcomposite-dev
sudo apt-get -y install qtscript5-dev

